export { StructureDetectorService } from './structure-detector.service';
export { NormalizerService } from './normalizer.service';
export { IngestionService } from './ingestion.service';
export { FileParserService } from './file-parser.service';
export { UploadService } from './upload.service';
export { SearchService } from './search.service';
export type { DetectedChunk } from './structure-detector.service';
export type { NormalizationStats } from './normalizer.service';
export type { JobStatusInfo } from './ingestion.service';
export type { ParsedFile } from './file-parser.service';
export type { UploadResult } from './upload.service';
export type { SearchResult, SearchOptions } from './search.service';
